Feat#99 subscribe info
softeerbootcamp-3rd/Team2-iFive pull request #110
Opened 2024-02-19 02:23 UTC by Win-9

## 구현내용

* 현재 픽업 정보중 부모의 응답 처리 내용을 변경하였습니다.
* 현재 픽업 정보중 기사의 응답 처리 내용을 변경하였습니다.
* 정책변경으로 인해 구독 요청 정보를 변경하였습니다.
    * 부모 아이 1대 1 매칭 변환으로 아이 이름은 요청하지 않도록 변경하였습니다.

---

원래의 Response에서 Json데이터를 내릴 때 Key 값이 한번 더 들어가게 하였는데, 프론트 개발자의 협의 결과 Key 값 없이 바로
데이터에 접근할 수 있도록 요청이 왔습니다.   
따라서 `@JsonUnwrapped`를 이용하여 Key값으로 감싸지 않고 값을 바로 보낼 수 있도록 하였습니다.

2024-02-19 09:45 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/repository/DriverRepository.java
저도 이 부분이 정말 고민이 많이 되었는데 최종적으로는 PickUpInfo를 조회하는 것이기 때문에 PickUpinfoRepository에 들어가 한다고 생각했었습니다. 그러나 부모repository 에서도 동일한 로직인데 조회되면 id만 달라지는 쿼리가 날아가기 때문에 역할 분리를 위해서 각각 driver와 parent로 분리되어야 한다고 생각했습니다.

그런데 경수님 의견도 들어보니 Pickinfo쪽에 넣는게 좋다고 생각한다고 하셔서 후에 리펙토링을 거칠 때 메소드 이름을 명확히 하여 PickUpInfo 하는 것도 좋은 방안 인 것 같습니다.

2024-02-20 01:16 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/repository/DriverRepository.java
저는 pickup 쪽에 넣어왔는데 경수님 의견도 비슷하군요 의견 감사합니다!

2024-02-20 01:42 UTC, Gyeongsu1997 requested changes

2024-02-20 01:42 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/repository/DriverRepository.java
> +                "AND pu.reservedTime >= CURRENT_TIMESTAMP";
예약 시간 이후에 조회를 하면 조회가 안되는거 아닌가요?

2024-02-20 01:42 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/dto/response/CurrentPickUpResponse.java
> +                .endDate(reservedTime.plusHours(1))
TimeInfo.of에서 .endTime(reservedTime.plusHours(1)) 이 부분이랑 헷갈리신것 같네요. 제거 부탁 드립니다.

2024-02-20 01:42 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/repository/DriverRepository.java
findAllRunningPickInfo와 findRunningPickInfo의 차이를 잘 모르겠습니다. 구두로 들은 설명에 의하면 findAllRunningPickInfo 하루의 모든 픽업 정보를 조회한다고 하셨는데 로직이 그렇게 보이지 않습니다. pu.startTime IS NOT NULL 조건으로 인해 이미 시작된 픽업만 조회가 가능할 것 같습니다.

2024-02-20 01:44 UTC, Gyeongsu1997 commented
@JsonUnwrapped를 사용하는 방법은 덕분에 처음 알게 되었습니다.

2024-02-20 01:46 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/dto/response/CurrentPickUpResponse.java
> +                .endDate(reservedTime.plusHours(1))
맞습니다. endDate 중첩되는 부분 바로 수정하도록 하겠습니다.

2024-02-20 02:15 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/repository/DriverRepository.java
findAllRunningPickInfo는 기사 입장에서 하루의 모든 픽업 정보를 조회합니다.
startTime의 업데이트 기준이 기사 입장에서의 요청 기준이 아니라 미리 삽입되는 데이터 기준으로 오해였습니다.
수정하도록 하겠습니다. 덕분에 심각한 오류를 잡을 수 있었습니다. 👍

2024-02-20 02:20 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/repository/DriverRepository.java
> +                "AND pu.reservedTime >= CURRENT_TIMESTAMP";
부등호 입력이 잘못되었습니다.
반영하도록 하겠습니다.

2024-02-20 03:18 UTC, merged