Feat#111 history
softeerbootcamp-3rd/Team2-iFive pull request #119
Opened 2024-02-19 17:37 UTC by Win-9

### 구현내용

부모 페이지의 구독 정보를 확인 한 이후 구독 정보를 누르면 다음 화면에 필요하게 되는   
PickUp에 대한 정보들을 볼 수 있는 API를 구현하였습니다.   

PathVariable로 PickupInfo의 ID를 넘기게되면 이를 조회하는 쿼리를 발생시킵니다.   

```java
public List<PickUp> findPickUpInfoByPickUpInfoIdAndParentId(Long parentId, long pickInfoId) {
        String query = "SELECT p FROM PickUp p\n" +
                "WHERE p.pickUpInfo.id =: pickInfoId\n" +
                "AND p.pickUpInfo.child.parent.id =: parentId\n" +
                "AND p.startTime IS NOT NULL\n" +
                "ORDER BY p.reservedTime DESC";
        return em.createQuery(query, PickUp.class)
                .setParameter("pickInfoId", pickInfoId)
                .setParameter("parentId", parentId)
                .getResultList();
    }
```
PickupinfoId와 부모의 ID를 통하여 현재 사용자에 대한 PickUpInfo를 조회합니다.   
이때 픽업이 시작된 내역들을 보여주어야 하므로 startTime의 값이 존재하는 경우를 추출합니다.   
또한 내림차순 정렬로 최근 내역들을 우선적으로 보여주도록 합니다.   

```java
@Builder
@Getter
public class PickUpHistoryResponse {
    private LocalDate date;
    private String day;
    private Info info;

    static public PickUpHistoryResponse toEntity(PickUp pickUp) {
        String time = pickUp.getReservedTime().toLocalTime().toString();
        return PickUpHistoryResponse.builder()
                .date(pickUp.getReservedTime().toLocalDate())
                .day(time + " " + pickUp.getReservedTime().getDayOfWeek())
                .info(Info.toEntity(pickUp))
                .build();
    }
```

응답 정보는 이와 같습니다.   
픽업이 시작되는 날을 기준으로 객체 값을 묶어서 보냅니다.   
day는 프론트 개발자의 요청에 따라서 요청 시간 정보와 해당하는 요일 정보를 보낼 수 있도록 하였습니다.   

```java
@Builder
    @Getter
    static class Info {
        private PickUpInfoStatus status;
        private LocalDateTime startTime;
        private String startImage;

        @JsonIgnore
        private LocalDateTime endTime;

        @JsonIgnore
        private String endImage;

        static Info toEntity(PickUp pickUp) {
            return Info.builder()
                    .startTime(pickUp.getStartTime())
                    .startImage(pickUp.getStartImage())
                    .endTime(pickUp.getEndTime())
                    .endImage(pickUp.getStartImage())
                    .status(pickUp.getEndTime() != null ? PickUpInfoStatus.DONE : PickUpInfoStatus.START)
                    .build();
        }
    }
```
PickUP정보는 픽업이 시작되면 start에 대한 정보가 업데이트 되고, 픽업이 끝나게되면 end에 대한 정보가 업데이터 됩니다.   
따라서 end에 대한 데이터 여부에 따라 완료, 진행중인 픽업 상태를 구분합니다.   
이때 아직 완료가 되지 않은 픽업 상태에 대해서는 end에 대한 데이터를 @JsonIgnore 처리로 보이지 않게 하였습니다.

2024-02-20 01:49 UTC, eekrwl requested changes
코드리뷰 완료했습니다!

2024-02-20 01:49 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/repository/PickUpRepository.java
> +    public List<PickUp> findPickUpInfoByPickUpInfoIdAndParentId(Long parentId, long pickInfoId) {
parentId는 Long형이고 pickInfoId는 long형인데 통일 시켜줘도 좋을 것 같습니다.
pickInfoId를 pickUpInfoId로 변경하는 것은 혹시 어떨까요? 
더 알아보기 쉬운 것 같습니다

2024-02-20 01:49 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/repository/PickUpRepository.java
> +    public List<PickUp> findPickUpInfoByPickUpInfoIdAndParentId(Long parentId, long pickInfoId) {
query에 \n을 넣는 이유가 있는지 궁금합니다.

2024-02-20 01:49 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/repository/PickUpRepository.java
메서드 이름이 길어지기는 하겠지만, 메서드 이름에 
```java
"AND p.startTime IS NOT NULL\n" +
                "ORDER BY p.reservedTime DESC";
```
이런 부분도 표현되어있으면 좋을 것 같습니다.

2024-02-20 01:49 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/dto/response/CurrentPickUpResponse.java
> +                .endDate(reservedTime.plusHours(1))
endDate가 두번 있는데 혹시 어떤 의미인지 여쭤봐도 될까요?
그리고 하루의 픽업이 아니라 픽업구독 만료날짜에 1시간을 더하는 부분이 잘 이해가 되지 않습니다

2024-02-20 01:49 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/dto/response/CurrentPickUpResponse.java
저희 전체적으로 dto에 무엇을 위한 것인지 주석을 달아도 좋을 것 같습니다.
비슷한 이름이 많아서 다른 사람이 봤을때 이해하기 쉽지않은 것 같아요

2024-02-20 01:49 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/dto/response/PickUpHistoryResponse.java
> +                    .status(pickUp.getEndTime() != null ? PickUpInfoStatus.DONE : PickUpInfoStatus.START)
하루의 픽업 상태를 말하는건지 헷갈립니다. 하루의 픽업이면 PickUpStatus로 이름을 변경하는 것은 어떨까요?

2024-02-20 01:49 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/entity/enums/PickUpInfoStatus.java
하루의 픽업을 말하는 것인지 이름이 조금 헷갈려서 PickUpStatus 와 같은 이름은 어떨지 궁금합니다.
PickUpInfo는 한달 간의 구독 기간 내내 사용해서 헷갈립니다.

2024-02-20 01:49 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/entity/enums/PickUpInfoStatus.java
픽업 구독 요청이 수락되면 pickup을 전부 생성해서 넣어놓는 것으로 알고 있는데, 상태가 시작/종료 두가지인지 궁금합니다.
시작전인 상태는 혹시 필요가 없을까요??

2024-02-20 01:49 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/repository/DriverRepository.java
> +    public List<Object[]> findAllRunningPickInfo(Long driverId) {
메서드명에 PickUpInfo는 어떨까요?

2024-02-20 01:49 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/dto/response/CurrentPickUpResponse.java
> +    private LocalDateTime endDate;
코드가 잘 이해가 가지 않습니다
아이가 실제로 탑승하고 하차한 시간을 나타내는 부분이면 Date보다 Time이 더 중심이 될 것 같은데 Time임을 이름에 나타내줘도 좋을 것 같습니다

2024-02-20 03:08 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/repository/PickUpRepository.java
> +    public List<PickUp> findPickUpInfoByPickUpInfoIdAndParentId(Long parentId, long pickInfoId) {
특별한 의미는 없는데 끝에를 구분해 놓는것이 눈에 익어서 개인적으로는 좋더라구요...
다들 별로이시면 지우도록 하겠습니다 😄

2024-02-20 03:09 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/repository/PickUpRepository.java
좀 더명확해지겠군요. 감사합니다

2024-02-20 03:09 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/repository/PickUpRepository.java
> +    public List<PickUp> findPickUpInfoByPickUpInfoIdAndParentId(Long parentId, long pickInfoId) {
반영하도록 하겠습니다

2024-02-20 03:20 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/dto/response/CurrentPickUpResponse.java
> +                .endDate(reservedTime.plusHours(1))
endTime부분을 endDate의 로직으로 잘못 기입하였습니다.
반영하도록 하겠습니다.

2024-02-20 03:25 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/dto/response/PickUpHistoryResponse.java
> +                    .status(pickUp.getEndTime() != null ? PickUpInfoStatus.DONE : PickUpInfoStatus.START)
PickUpStatus가 이미 다른 엔티티 상태에 사용하고 있기 때문에 이름을 현재와 같이 사용하고 있습니다.

2024-02-20 03:26 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/entity/enums/PickUpInfoStatus.java
앗 그부분은 프론트 개발자와 논의과정에서 두가지 상태로 나타나도록 하였습니다 😄

2024-02-20 03:27 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/repository/DriverRepository.java
> +    public List<Object[]> findAllRunningPickInfo(Long driverId) {
반영하도록 하겠습니다 👍

2024-02-20 04:45 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/dto/response/CurrentPickUpResponse.java
> +    private LocalDateTime endDate;
넵 좋습니다.
주석도 달아서 이해가 되도록 하는게 좋을 것 같습니다.

2024-02-20 08:49 UTC, Gyeongsu1997 requested changes

2024-02-20 08:49 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/repository/PickUpRepository.java
> +    public List<PickUp> findPickUpInfoByPickUpInfoIdAndParentIdOrderByReservedTime(Long parentId, Long pickInfoId) {
PickUpInfo entity가 아니라 PickUp entity를 조회하는 메서드이기 때문에 메서드 이름을 findPickUpBy...로 하는게 더 적절할 것 같습니다.

2024-02-20 08:49 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/dto/response/PickUpHistoryResponse.java
> +    static public PickUpHistoryResponse toEntity(PickUp pickUp) {
public static으로 쓰는게 일반적인 것 같은데 static public으로 쓰시는 이유가 있나요?

2024-02-20 08:49 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/dto/response/PickUpHistoryResponse.java
> +                    .endImage(pickUp.getStartImage())
.endImage(pickUp.getStartImage())를 .endImage(pickUp.getEndImage())로 수정해야 합니다.

2024-02-20 08:49 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/dto/response/CurrentPickUpResponse.java
> +                    .pickUpStartTime(reservedTime)
위 주석이 잘못된 것인가요? resevedTime은 실제 픽업 시작 시간이 아니라 예약 시간이 맞지 않나요?

2024-02-20 08:49 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/dto/response/CurrentPickUpResponse.java
정책 변경으로 인해 modifiedDate는 실제 수정(기사의 승인 또는 거절)이 이루어진 날짜가 기록되고 expiredDate는 구독이 마감되는 날짜(modifiedDate부터 29일 후)가 기록됩니다. 따라서 .startDate(pickUpInfo.getPickUpSubscribe().getModifiedDate())를 .startDate(pickUpInfo.getPickUpSubscribe().getModifiedDate().plusDays(1))으로  .endDate(pickUpInfo.getPickUpSubscribe().getExpiredDate())를 .endDate(pickUpInfo.getPickUpSubscribe().getExpiredDate().minusDays(1))으로 변경해야 할 것 같습니다.

2024-02-21 07:39 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/repository/PickUpRepository.java
> +    public List<PickUp> findPickUpInfoByPickUpInfoIdAndParentIdOrderByReservedTime(Long parentId, Long pickInfoId) {
좋은 지적인 것 같습니다. 반영하겠습니다.

2024-02-21 07:43 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/dto/response/PickUpHistoryResponse.java
> +    static public PickUpHistoryResponse toEntity(PickUp pickUp) {
https://stackoverflow.com/questions/2832126/quick-java-question-about-private-static-final-keywords-for-fields#21501788
궁금해서 찾아보니 언급하신 컨벤션 규칙도 존재하네요!
PSF라고 보편적으로 사용하는 것 같습니다.
반영하도록 하겠습니다.

2024-02-21 08:16 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/repository/PickUpRepository.java
> +    public List<PickUp> findPickUpInfoByPickUpInfoIdAndParentId(Long parentId, long pickInfoId) {
통일하는게 좋을 것 같긴하지만 동작에는 크게 상관없을 것 같습니다!
코드에서도 + 기호와 엔터로 구분되어 특별한 이유가 있는지 잠시 궁금했습니다.

2024-02-21 08:17 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/dto/response/PickUpHistoryResponse.java
> +                    .status(pickUp.getEndTime() != null ? PickUpInfoStatus.DONE : PickUpInfoStatus.START)
아 다른 사용이 있군요 알겠습니다!

2024-02-21 08:18 UTC, eekrwl approved these changes

2024-02-21 08:19 UTC, Gyeongsu1997 approved these changes
고생하셨습니다!

2024-02-21 08:21 UTC, merged