Feat#120 push alarm
softeerbootcamp-3rd/Team2-iFive pull request #142
Opened 2024-02-22 07:50 UTC by Win-9

### 구현내용

각 사용자마다 올바른 push 알림이 가도록 구현하였습니다.   

우선 FCM토큰이 필요한데 이는 로그인 이후 프론트측에서 /menu경로로 요청하여 저장할 있도록 하였습니다.   
따라서 해당 url에 대한 필터처리를 구현하였습니다.

```java
public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException {
        HttpServletRequest httpServletRequest = (HttpServletRequest) request;
        if (isBlackList(httpServletRequest.getRequestURI()) && (httpServletRequest.getMethod().equals("POST"))) {
            try {
                String userId = (String) request.getAttribute(JwtAuthorizationFilter.USER_ID);
                TokenRequest tokenRequest = objectMapper.readValue(request.getReader(), TokenRequest.class);
                log.info("user = {}, fcmToken = {}", userId, tokenRequest.getFcmToken());
                userService.updateFCMToken(userId, tokenRequest.getFcmToken());
               ...
    }
```

토큰을 저장한다면 토큰을 저장한 사용자에게 푸시알림이 가능합니다.

```java
static public void createNotification(Users user, String title, String message) throws ExecutionException, InterruptedException {
        if (user.getFcmToken() == null) {
            log.error("user = {}, FCM토큰이 없습니다", user.getUserId());
            return;
        }

        NotificationRequest request = NotificationRequest.builder()
                .title(title)
                .token(user.getFcmToken())
                .message(message)
                .build();
        sendNotification(request);
    }
```

토큰이 존재한다면 `sendNotification`을 통하여 원하는 title과 message를 통해 알림을 줄 수 있습니다.   

또한 알림테이블을 구현하여 픽업 1시간 전의 기사에게는 해당 알림이 가능하도록 하였습니다.   
알림테이블은 기사가 픽업 승인할 때 동시에 생성하고 스케쥴을 이용하여 해당 테이블은 매 분마다 스캔을 하도록 하였습니다.   
이후 시간을 비교하여 알림을 보낸 후 해당 레코드는 테이블에서 제거하도록 합니다.

```java
@Scheduled(cron = "0 * * * * *")
    @Transactional
    public void checkPickUpTime() throws ExecutionException, InterruptedException {
        List<Notification> notificationList = notificationRepository.findAllNotification();
        for (Notification notification : notificationList) {
            NotificationUtill.createNotification(notification.getDriver()
                    , AlarmMessage.PICK_UP_PRE_INFO.getTitle(), AlarmMessage.PICK_UP_PRE_INFO.getMessage());
            notificationRepository.deleteById(notification.getId());
        }
    }
```

2024-02-22 18:40 UTC, eekrwl requested changes

2024-02-22 18:40 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/config/FCMConfig.java
> +    private String FIREBASE_CONFIG_PATH;
fcm.yml 다른 채널로 공유해주시면 로컬에서 직접 사용해볼 수 있을 것 같습니다 😄

2024-02-22 18:40 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/fcm/AlarmMessage.java
> +    PICK_UP_PRE_INFO("픽업 알림 안내", "픽업 예정까지 한 시간 남았습니다.")
픽업 사전 안내, 픽업 시작까지 한 시간 남았습니다. 와 같은 문구는 어떨까요? 예정까지 한시간 남았다는 말이 조금 어색한가 싶기도 합니다 😀

2024-02-22 18:40 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/fcm/NotificationUtill.java
> +            log.error("user = {}, FCM토큰이 없습니다", user.getUserId());
제가 fcm에 대해서 잘 몰라서 위에 코드에서 토큰이 있음을 확인했는데 다시 토큰이 없을 수도 있는지 궁금합니다.

2024-02-22 18:40 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/repository/DriverRepository.java
> +                "ORDER BY pu.reservedTime ASC";
제목에 정렬관련 내용이 표시되면 더 명확할 것 같습니다 👍

2024-02-22 18:40 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/repository/NotificationRepository.java
> +                "WHERE n.pickUpTime <= CURRENT_TIME";
단순히 모든 Notification을 조회하는 코드는 아닌 것 같아서 마찬가지로 해당 내용을 메서드 이름에 표현해주셔도 좋을 것 같습니다 👍

2024-02-22 18:40 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/service/PickUpService.java
> +        Parent parent = pickUp.getPickUpInfo().getChild().getParent();
PickUp 클래스 내에 getParent()와 같은 메서드를 만들어두고 사용하는 것은 어떨까요?
get이 3번 중첩되어있어 가독성이 조금 떨어지는 것 같습니다.
저희 서비스 특성 상 픽업에서 부모 기사 아이를 가져올 일이 굉장히 많기 때문에 getParent를 만들어서 사용해도 좋을 것 같습니다 👍

2024-02-22 18:40 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/service/PickUpService.java
> +                    AlarmMessage.PICK_UP_END.getMessage());
## 이 부분은 픽업이 시작되는 부분이라 AlarmMessage가 전부 PICK_UP_START로 들어가야 할 것 같습니다 😮

2024-02-22 18:40 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/service/PickUpService.java
> +                    AlarmMessage.PICK_UP_END.getMessage());
## 이 부분은 픽업이 종료되는 부분이라 AlarmMessage가 전부 PICK_UP_END로 들어가야 할 것 같습니다 😮

2024-02-22 18:41 UTC, eekrwl commented
푸시 알림 처음 사용해보셨음에도 빠르게 잘 구현하신 것 같습니다!
후에 여유있을 때 해당 내용 위키에 공유해주시면 좋을 것 같습니다 😄

2024-02-23 01:38 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/config/FCMConfig.java
> +    private String FIREBASE_CONFIG_PATH;
바로 올려드리겠습니다

2024-02-23 01:48 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/fcm/AlarmMessage.java
> +    PICK_UP_PRE_INFO("픽업 알림 안내", "픽업 예정까지 한 시간 남았습니다.")
더 정확해 보입니다. 
반영하도록 하겠습니다 👍

2024-02-23 01:55 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/fcm/NotificationUtill.java
> +            log.error("user = {}, FCM토큰이 없습니다", user.getUserId());
FCM토큰이 존재해야 알림이 가능합니다.
FireBase쪽에서 토큰을 받아오지 못하거나 토큰 저장시 오류가 나서 valid오류가 생길 수 있읍니다.
이때 토큰이 없어도 다른 서비스로직 응답은 정상적으로 작동해야 하므로 로그만을 출력하도록 하였습니다.

2024-02-23 01:56 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/repository/DriverRepository.java
> +                "ORDER BY pu.reservedTime ASC";
네이밍을 더 고려해야하는데 제 작명센스가 너무 좋지 않군요ㅜ
더 노력하겠습니다 😢

2024-02-23 02:08 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/service/PickUpService.java
> +                    AlarmMessage.PICK_UP_END.getMessage());
헉 바로 변경하였습니다. 🐱

2024-02-23 02:43 UTC, Gyeongsu1997 requested changes

2024-02-23 02:43 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/fcm/AlarmMessage.java
> +    PICK_UP_PRE_INFO("픽업 알림 안내", "픽업 예정까지 한 시간 남았습니다.")
저도 동의합니다.

2024-02-23 02:43 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/fcm/NotificationUtill.java
> +            log.error("user = {}, FCM토큰이 없습니다", user.getUserId());
저도 궁금합니다. 토큰이 잘못된 형식이라면 더 적절한 로그를 출력하는게 좋을것 같습니다.

2024-02-23 02:43 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/dto/request/NotificationRequest.java
NotificationUtil 클래스 내부에서만 사용되는것 같은데 inner class로 만들어서 사용하거나 fcm 패키지로 이동시키는 것도 좋을것 같습니다.

2024-02-23 02:43 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/service/DriverService.java
# removeOverlappedSubscribe 메서드에서 거절되는 요청에도 거절 알림을 보내야 합니다.

2024-02-23 02:43 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/service/ParentService.java
> +    private void createPickUp(LocalDateTime localDateTime, PickUpInfo pickUpInfo) {
createPickUp 메서드는 DriverService에 있으니 없어도 될 것 같습니다.

2024-02-23 02:43 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/service/ParentService.java
> +                .expiredDate(LocalDateTime.now().plusDays(1).plusWeeks(4))
expiredDate를 여기서 설정하면 안됩니다. 제거해서 be 브랜치에 merge했는데 다시 들어가 있네요. 제거 부탁드립니다.

2024-02-23 02:49 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/repository/DriverRepository.java
> +    public List<Driver> findDriversBySchedule(DriverListRequest driverListRequest) {
해당 메서드도 삭제해도 되는 메서드입니다.

2024-02-23 03:07 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/entity/Notification.java
> +    private LocalDateTime pickUpTime;
반영하였습니다 :-)

2024-02-23 03:09 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/dto/request/NotificationRequest.java
이너클래스로 선언하기보다는 분리를 시키는게 좋을 것 같아 패키지 이동이 좋은 방법이겠네요 👍

2024-02-23 03:10 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/service/ParentService.java
> +    private void createPickUp(LocalDateTime localDateTime, PickUpInfo pickUpInfo) {
수정하고 제가 삭제를 하지 않았군요
삭제하도록 하겠습니다 😺

2024-02-23 03:11 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/service/ParentService.java
> +                .expiredDate(LocalDateTime.now().plusDays(1).plusWeeks(4))
conflig해결하는 과정에서 잘 못 들어간 것 같습니다
해결하도록 하겠습니다 😃

2024-02-23 04:40 UTC, merged