Feat#15 login
softeerbootcamp-3rd/Team2-iFive pull request #39
Opened 2024-02-09 04:16 UTC by Gyeongsu1997

## 구현 내용
- 회원가입
- 로그인
- 인가

## 기타
- 기존에 설계한 ERD에 변경이 발생합니다. driver와 parent 테이블에 공통적으로 user_id, password, role, refresh_token라는 컬럼이 추가됩니다.
- application.yml에 spring.main.allow-bean-definition-overriding=true라는 설정이 추가되었습니다. 배포시 유의해야 합니다.
- build.gradle에 jjwt 라이브러리가 추가되었습니다.

2024-02-10 19:33 UTC, eekrwl requested changes
코드리뷰 했습니다!
의견 남겨주시면 확인하겠습니다:)

2024-02-10 19:33 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/dto/TokenRefreshDto.java
#### 클래스 이름이 헷갈리는 것 같습니다.

리프레시 토큰으로 새 엑세스 토큰을 요청할 때 사용하는 토큰인 것 같은데
dto이름에서 무엇을 하는 dto인지 알아보기 조금 어려운 것 같습니다.

2024-02-10 19:33 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/controller/AuthController.java
#### 새로 만들어진 액세스 토큰 이름

jwt도 이해가 가긴 하지만 newAccessToken같이 조금 더 새로 만들어진 토큰임을 명시해줘도 좋을 것 같습니다.

2024-02-10 19:33 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/dto/UserRegisterDto.java
#### 객체 생성자에서 정보를 넣는 것은 어떨까요?

```java
Driver driver = new Driver();
driver.setUserInfo(userId, password, name, phone, Role.DRIVER);
```
위의 정보들을 한번에 바꿀 일은 없을 것 같아서 setUserInfo 메서드는 한번만 사용될 것 같습니다.
생성자로 넣어서
```java
Driver driver = new Driver(userId, password, name, phone, Role.DRIVER);
```
위와 같이 만드는 것은 혹시 어떨까요?

2024-02-10 19:33 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/jwt/JwtProvider.java
# secret key를 github에 올리면 안될 것 같습니다

```java
public static final byte[] secret = "IDropSecretKeyIDropSecretKeyIDropSecretKey".getBytes();
```
이 부분이 secret key인 것 같은데 깃허브에 올라가면 안됩니다
시크릿 키를 변경후 jwt.yml과 같은 파일을 만들어 빼야 할 것 같습니다.

2024-02-10 19:33 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/repository/UserRepository.java
#### 우리 스프링데이터jpa 사용하면 안되는 거겠죠??ㅠㅠ

너무 슬퍼요
그런데 querydsl은 사용해도 된다는데..
보통 spring data JPA랑 같이 쓰긴 한다는데 흑흑

2024-02-10 19:33 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/repository/UserRepository.java
#### 리프레시 토큰 분리

```java
List<Driver> driverResultList = em.createQuery("select d from Driver d where d.refreshToken = :refreshToken", Driver.class)
                .setParameter("refreshToken", refreshToken)
                .getResultList();

List<Parent> parentResultList = em.createQuery("select p from Parent p where p.refreshToken = :refreshToken", Parent.class)
                .setParameter("refreshToken", refreshToken)
                .getResultList();
```
두 번 찾으려니 번거로운 것 같은데 refreshToken은 따로 테이블로 빼도 좋을 것 같습니다.

2024-02-10 19:33 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/filter/JwtAuthorizationFilter.java
#### 주석 달아주시면 너무 좋을 것 같습니다

메서드 하나당 코드가 긴데 무슨 코드인지 잘 모르겠어서 주석 달아주시면 이해가 조금 더 쉬울 것 같습니다

2024-02-10 19:33 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/filter/JwtFilter.java
#### 주석 달아주시면 너무 좋을 것 같습니다

메서드 하나당 코드가 긴데 무슨 코드인지 잘 모르겠어서 주석 달아주시면 이해가 조금 더 쉬울 것 같습니다

2024-02-10 19:33 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/filter/VerifyUserFilter.java
#### 주석 달아주시면 너무 좋을 것 같습니다

메서드 하나당 코드가 긴데 무슨 코드인지 잘 모르겠어서 주석 달아주시면 이해가 조금 더 쉬울 것 같습니다
사용자 인증과 관련된 필터가 여러개인 것 같은데 각각이 무슨 역할인지 알아보기가 어렵습니다ㅠㅠ

2024-02-11 02:34 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/entity/enums/Role.java
name으로 수정하겠습니다.

2024-02-11 02:40 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/controller/UserController.java
기사 정보 추가 등록, 부모의 아이 정보 등록 등을 추후에 구현할 예정인데 register라고 하면 헷갈릴 여지가 있겠네요. signUp으로 수정하겠습니다.

2024-02-11 04:23 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/jwt/JwtProvider.java
까먹고 있었네요. secret key와 토큰 만료 시간에 대한 정보를 설정 파일로 분리했습니다.

2024-02-11 04:26 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/entity/Users.java
user를 예약어로 사용하는 일부 데이터베이스가 있습니다. 현재는 user 테이블이 생성되지 않지만 user 테이블이 필요한 경우가 생길 수 있으므로 Users로 하는게 좋아보입니다.

2024-02-11 04:48 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/entity/Users.java
메소드를 만들어 놓고 안쓰고 있었네요. User의 password를 외부에서 getter로 반환받아서 비교하는 것보다 속성을 가지고 있는 도메인 내부에서 비교하는 것이 나을것 같습니다.

2024-02-11 05:41 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/exception/ErrorCode.java
감사합니다

2024-02-11 06:20 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/dto/TokenRefreshDto.java
TokenRefreshRequest로 수정하였습니다.

2024-02-11 06:22 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/entity/Users.java
좋은 의견이지만 그렇게 한다면 코드에 큰 변동이 발생할것 같습니다. 차후에 고려해 보도록 하겠습니다.

2024-02-11 06:23 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/repository/UserRepository.java
좋은 의견이지만 그렇게 한다면 코드에 큰 변동이 발생할것 같습니다. 차후에 고려해 보도록 하겠습니다.

2024-02-11 06:25 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/dto/UserRegisterDto.java
Driver와 Parent 클래스에 각각 생성자를 만드는 것보다 공통의 상위 클래스인 Users에서 메서드로 한번에 정의하는게 더 낫다고 생각했습니다.

2024-02-11 06:27 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/repository/UserRepository.java
Spring data JPA는 사용하면 안되는 것으로 알고 있습니다. Querydsl은 전에 사용해 본 적이 없어서 적용하려면 추가적인 공부 시간이 많이 필요할 것 같아서 일단은 사용하지 않으려고 합니다.

2024-02-11 06:29 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/entity/Users.java
저는 this를 쓰는 것이 인스턴스 필드라는 것을 한눈에 알 수 있어서 좋은것 같습니다.

2024-02-11 06:32 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/controller/AuthController.java
newlyCreatedJwt로 수정하였습니다.

2024-02-11 06:35 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/service/UserService.java
createNewJwtFromRefreshToken으로 수정했습니다.

2024-02-11 06:39 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/controller/UserController.java
이야기해 볼만한 주제네요. 저는 어느쪽으로 해도 상관 없을 것 같지만 승구님의 의견도 궁금합니다.

2024-02-11 06:43 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/service/UserService.java
현재는 회원가입, 로그인, 토큰 재발급 등과 같은 로직들이 있습니다. 모두 인증, 인가에 관한 기능이라 하나의 서비스 클래스에서 처리하는 것이 어색하지 않은 것 같습니다. 나중에 추가될 비즈니스 로직은 DriverService, ParentService를 따로 만들어서 처리하면 되므로 우선은 그냥 두겠습니다.

2024-02-11 06:52 UTC, Gyeongsu1997 commented
## 수정사항
- 채완님이 피드백하신 대로 일부 클래스, 메소드, 변수명 수정
- jwt secret key와 토큰 만료 시간을 설정 파일로 분리(슬랙에 파일 올리겠습니다.)
- 로그인한 사용자 정보를 controller에서 쉽게 사용할 수 있도록 애노테이션과 argument resolver 구현

2024-02-11 07:34 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/entity/Users.java
넵 알겠습니다

2024-02-11 07:35 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/entity/Users.java
User가 이미 있나보군요 알겠습니다

2024-02-11 08:14 UTC, Win-9 reviewed
리뷰 해보았습니다.
다른 의견들 있으시면 모여서 의견 나누면 좋을 것 같습니다 :-)

2024-02-11 08:14 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/repository/UserRepository.java
> +    }
메소드 내용을 보면 전체 레코드를 가져오는 내용인데
개인적으로는 복수명사보다는 findAll**의 형식으로 네이밍 하는 것이 좋아보입니다 :-)
어떻게 생각하시나요??

2024-02-11 08:23 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/jwt/JwtProvider.java
새로운 key로 변경하였습니다.

2024-02-11 08:27 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/entity/Users.java
> +    }
Driver와 Parent에 각각 생성자를 만들어주는 것보다 메서드를 상속받아서 사용하는게 더 낫다고 생각했습니다. 상위 클래스에 있는 속성을 초기화하는 것이기 때문입니다.

2024-02-11 08:28 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/repository/UserRepository.java
> +    }
좋은 생각입니다. 향후 findDriversBySchedule과 같이 특정 조건으로 검색하는 메소드가 추가된다면 findAllDrivers로 네이밍을 수정하는게 좋을것 같습니다.

2024-02-11 08:30 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/service/UserService.java
> +                return null;
좋은 정보 감사합니다.

2024-02-11 08:37 UTC, merged

2024-02-11 09:36 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/filter/JwtAuthorizationFilter.java
> +    }
좋은 의견같습니다