Feat#50 subscribe
softeerbootcamp-3rd/Team2-iFive pull request #81
Opened 2024-02-15 05:14 UTC by Win-9

### 구현내용

구독요청을 받기위한 controller와 하위 비즈니스 로직을 구현하였습니다.   

요청을 받을 때 다음과 같은 Request를 받습니다.
```java
public class SubscribeRequest {
    private Long driverId;
    private String childName;
    private String startAddress;
    private Double startLongitude;
    private Double startLatitude;
    private String endAddress;
    private Double endLongitude;
    private Double endLatitude;
    private String requestDate;
}
```

주의해야할 점은 요청 정보는 사전에 논의된 규칙에 따라 JSON으로 된 String을 받습니다.   
해당 JSON은 Parser클래스의 메소드에서 파싱 후 LocalDateTime의 List를 반환하게 됩니다.   
파싱시 현재 날짜 기준으로 현재 이후에  가장 가까운 요일에 매칭된 날짜를 가져옵니다.

```java
static private LocalDate findNearDateByday(DayOfWeek day) {
        LocalDate today = LocalDate.now();
        return today.with(TemporalAdjusters.next(day));
    }
```

이후 만료날짜를 체크하며 만료날짜보다 이전이면 List를 만들게 됩니다.
```java
while (keys.hasNext()) {
            String key = keys.next();
            DayOfWeek dayOfWeek = DayOfWeek.valueOf(Days.getDayEnum(key));   // 날짜를 DayOfWeek 타입으로 변환
            JSONObject timeObj = scheduleJson.getJSONObject(key);
            LocalDate date = findNearDateByday(dayOfWeek);  // 가장 인접한 날짜 탐색

            for (int i = 0; i < 4; i++) {
                LocalDateTime dateTime = LocalDateTime.of(date, LocalTime.of(timeObj.getInt("hour"), timeObj.getInt("min")));
                scheduleList.add(dateTime);
                date = date.plusWeeks(1);
                if (date.isAfter(ChronoLocalDate.from(expiredDate))) {
                    break;
                }
            }
        }
        return scheduleList;
```

---

구독요청시 유효성 검사 이후 subscribe을 생성합니다.   
이때 정책에 따라서 대기중인 상태를 무조건 승인이 되도록 변경하였습니다.   

```java
private PickUpSubscribe createPickUpSubscribe() {
        PickUpSubscribe subscribe = PickUpSubscribe.builder()
                .status(PickUpStatus.ACCEPT)
                .requestDate(LocalDateTime.now().plusDays(1))
                .expiredDate(LocalDateTime.now().plusDays(1).plusWeeks(4))
                .build();
        pickUpRepository.savePickUpSubscribe(subscribe);
        return subscribe;
    }
```

이후 연관된 Location과 PickUpInfo를 생성 후에 PickUpInfo에서 연관관계 메소드를 이용하여 관계를 정리하게 됩니다.   
```java
private PickUpInfo createPickUpInfo(SubscribeRequest subscribeRequest, Optional<Child> child, Optional<Driver> driver, PickUpLocation location, PickUpSubscribe subscribe) {
        PickUpInfo pickUpInfo = PickUpInfo.builder()
                .child(child.get())
                .driver(driver.get())
                .schedule(subscribeRequest.getRequestDate())
                .pickUpLocation(location)
                .build();
        pickUpInfo.updatePickUpSubscribe(subscribe);
        pickUpInfo.updatePickUpLocation(location);
        pickUpRepository.savePickUpInfo(pickUpInfo);
        return pickUpInfo;
    }
```

Paser에서 가져온 스케쥴 정보들을 이용하여 PickUp정보를 생성하여 저장합니다.  
이때 사전 논의로 변경된 테이블들의 연관성을 반영하여 Subscribe가 아닌 PickUpInfo와 연관 관계를 가지도록 하였습니다.

```java
private void createPickUp(LocalDateTime localDateTime, PickUpInfo pickUpInfo) {
        PickUp pickUp = PickUp.builder()
                .reservedTime(localDateTime)
                .build();
        pickUp.updatePickUpInfo(pickUpInfo);
        pickUpRepository.savePickUp(pickUp);
    }
```

---
BaseResponse에 대한 메소드를 추가로 구현하였습니다.

```java
public static <T> BaseResponse<T> success() {
        return new BaseResponse<>("Data Successfully Proceed");
    }
```

해당 BaseResponse클래스 안 success()를 만들었습니다.

Post 이후 특별한 데이터 응답 없이 성공적으로 데이터를 보냈다는 응답을 보내고싶을 때 success()를 사용하면 기본적으로 설정된 성공 응답메시지가 전달됩니다.

제네릭타입인 data는 `@JsonInclude(JsonInclude.Include.NON_NULL)` 로 되어있어서 null이면 응답에 추가되지 않도록 변경하였습니다.

2024-02-15 07:03 UTC, Gyeongsu1997 requested changes

2024-02-15 08:29 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/service/ParentService.java
> +        checkChildExist(child);
Opional을 잘 활용하는 예시인 것 같습니다.
적용해보도록 하겠습니다 😄

2024-02-15 08:31 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/service/ParentService.java
> +                .requestDate(LocalDateTime.now().plusDays(1))
이 부분이 제대로 논의되기 이전에 구성된 로직이라 아직 반영이 안되었습니다.
바로 적용하겠습니다 👍

2024-02-15 08:33 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/repository/DriverRepository.java
> +        return em.createQuery("select d From Driver d where d.id =: id", Driver.class)
Optional에 대한 좋은 메소드가 많이 있네요!
Optional을 좀 더 공부해봐야겠습니다 🖥️

2024-02-15 08:34 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/service/ParentService.java
> +        pickUpInfo.updatePickUpLocation(location);
리펙토링 하는 과정에서 의도를 더 명확히 하기 위해서 메소드를 구성하고 추가했는데, 그 전에 Builder에서 적용하던 부분을 삭제를 누락하였습니다. 바로 수정하겠습니다.

2024-02-16 02:16 UTC, eekrwl reviewed
리뷰 완료했습니다 고생하셨습니다!

2024-02-16 02:18 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/repository/PickUpRepository.java
> +    @Transactional
Service층에 반영해야 할 것을 Repository층에 잘못 설정하였습니다.
수정하도록 하겠습니다.

2024-02-16 02:18 UTC, merged