Feat#65 child info lookup
softeerbootcamp-3rd/Team2-iFive pull request #86
Opened 2024-02-16 02:54 UTC by eekrwl

## 요약
- (기사/부모) 각각의 메인 페이지에 필요한 아이 픽업 정보 api 구현

<br>

## 고민한 점
### 1. join or 자바 코드
정보를 하나 가져오기 위해 여러 테이블이 필요합니다.
두가지 방법을 생각했습니다.
#### - repository에서 Join을 여러번 해서 한번에 가져오기

한 번에 조회해서 가져오니 데이터베이스 접근 횟수 자체는 적어질 것 같습니다.
하지만 service 단계에서는 아무 비즈니스 로직이 없고 그저 repository를 호출하게 됩니다.
repository에서 만든 메서드는 재사용성이 매우 떨어집니다.

#### - repository에서는 작은 단위로 가져오고 service에서 자바 코드로 정보 조회하기

조금 작은 단위로 repository 메서드를 작성하기 때문에 재사용성이 좋습니다.
service 단계에서 어떤 비즈니스 로직이 돌아가고 있는지 확인할 수 있습니다.
한 정보를 찾기 위해 계속 데이터베이스를 조회해서 성능에 문제가 있을지 살짝 걱정됩니다.
    
고민하다가 2번 방식으로 코드를 작성하려고 노력해보았습니다.
팀원들의 의견도 궁금해서 많은 의견 남겨주시면 감사할 것 같습니다.

### 2. dto 사용 범위
dto를 controller에서만 사용하려다 보니 아래와 같이 .get 이 반복되는데 괜찮은 방식인지 의견이 궁금합니다.
```java
.startAddress(pi.getPickUpLocation().getStartAddress())
.endAddress(pi.getPickUpLocation().getEndAddress())
```

<br>

## 코드 흐름 간단 설명
- repository : driverId, childId에 따라 해당하는 픽업을 전부 조회합니다.
- service : repository에서 조회한 픽업 중 조건에 맞는 픽업을 골라냅니다.
- controller : 골라낸 픽업을 dto 모양에 맞춰 정리해서 응답합니다.

2024-02-16 03:22 UTC, Win-9 reviewed
전체적으로 깔끔한 로직 잘 보았습니다.

DTO의 경우 드미터의 법칙에 따라서 get을 계속 사용하는 것이 좋지 않기 때문에 저도 고민이 되는데 
저는 Static Class를 사용해서 한번 따로 분리를 해주는 편 입니다.

```java
static public CurrentPickUpResponse of(PickUpInfo pickUpInfo) {
        return CurrentPickUpResponse.builder()
                .childName(pickUpInfo.getChild().getName())
                .childImage(pickUpInfo.getChild().getImage())
                .destination(Destination.of(pickUpInfo.getPickUpLocation()))
                .build();
    }


    static class Destination {
        private Double startLatitude;
        private Double startLongitude;
        private String startAddress;
        private Double endLatitude;
        private Double endLongitude;
        private String endAddress;

            ...
}
```

하위 클래스를 두지 않으면 getLocation().getAddress()와 같이 계속 get으로 들어가기 때문에 한번 분리를 하면 하위에서 get을 사용하기 때문에 상단에서는 이를 방지할 수 있었습니다.   

그래도 이 방식이 원초적 해결이 아니라 우회적인 방법이라 다른 방법도 고민해봐야 할 것 같습니다...

다른 개발자분들은 어떻게 처리하시는지 궁금하군요 😢

2024-02-16 03:22 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/controller/PickUpController.java
> +        }).collect(Collectors.toList());
이 부분을 Service층에서 처리할 지, Controller층에서 처리할 지 고민이 생깁니다.   
정확히 어떤 부분이 좋다는 답은 없으니 논의 후에 결정하면 좋을 것 같습니다.

### BaseResponse

응답 시에 BaseResponse를 하셔야 할 것 같습니다.

2024-02-16 03:22 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/controller/PickUpController.java
> +        Driver driver = (Driver) user;
@Login에서 User가 아니라 하위의 타입을 명시해서 사용하면 Filter쪽에서 에러 처리가 가능해지니
이 부분은 하위 타입을 사용하는데 어떨까요?? 👍

2024-02-16 03:22 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/repository/PickUpRepository.java
> +        return query.getResultList();
TypedQuery와 getResultList()를 분리하신 이유가 있을까요??
저와는 다르게 구현하셔서 궁금한 점입니다 👍

2024-02-16 03:22 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/websocket/location/LocationWebSocketHandler.java
> +        System.out.println(session.getHandshakeHeaders().get("Sec-Websocket-Protocol"));
Sout보다 Log를 사용하시면 좋을 것 같습니다

2024-02-16 03:22 UTC, Win-9 commented on BE/iDrop/src/main/java/ifive/idrop/service/PickUpService.java
> +                .collect(Collectors.toList());
꽤 어려운 Stream Map처리인데 잘 구현하신 것같습니다.
저는 스트림 처리가 많이 부족한데 덕분에 공부하고 갑니다 👍

2024-02-16 03:22 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/websocket/location/LocationWebSocketHandler.java
> +        System.out.println(session.getHandshakeHeaders().get("Sec-Websocket-Protocol"));
여러 브랜치를 오가며 작업하던 중 코드가 섞인 것 같습니다. 삭제하겠습니다!

2024-02-17 06:42 UTC, Gyeongsu1997 requested changes

2024-02-17 06:42 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/controller/PickUpController.java
> +            throw new CommonException(ErrorCode.INVALID_ROLE_OF_USER);
ErrorCode.INVALID_ROLE_OF_USER는 회원가입 과정에서 사용되는 오류로 "회원의 역할이 정확하지 않습니다."라는 메시지와 "역할은 '기사' 또는 '부모' 중 하나여야 합니다."라는 솔루션을 응답합니다. 이 부분에서 사용하기에는 적절하지 않은 것 같습니다. 다른 ErrorCode를 만들어서 사용했으면 좋겠습니다.

2024-02-17 06:42 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/controller/PickUpController.java
> +            throw new CommonException(ErrorCode.INVALID_ROLE_OF_USER);
ErrorCode.INVALID_ROLE_OF_USER는 회원가입 과정에서 사용되는 오류로 "회원의 역할이 정확하지 않습니다."라는 메시지와 "역할은 '기사' 또는 '부모' 중 하나여야 합니다."라는 솔루션을 응답합니다. 이 부분에서 사용하기에는 적절하지 않은 것 같습니다. 다른 ErrorCode를 만들어서 사용했으면 좋겠습니다.

2024-02-17 06:42 UTC, Gyeongsu1997 commented on BE/iDrop/src/main/java/ifive/idrop/controller/PickUpController.java
> +                            .childImage(child.getName())
.childImage(child.getName())를 .childName(child.getName())으로 수정해야 합니다.

2024-02-18 05:32 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/controller/PickUpController.java
> +        }).collect(Collectors.toList());
네 수정완료했습니다!

2024-02-18 05:33 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/controller/PickUpController.java
> +        Driver driver = (Driver) user;
네 좋은 생각인 것 같습니다. 수정하겠습니다!

2024-02-18 05:37 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/repository/PickUpRepository.java
> +        return query.getResultList();
가독성을 고려하여 작성해보았습니다! 코드를 읽는 사람이 쿼리의 설정(예: 쿼리 문자열, 파라미터 설정 등)과 결과를 가져오는 작업을 분명하게 구분할 수 있으면 좋을 것 같아 이렇게 작성하였습니다

2024-02-18 05:39 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/controller/PickUpController.java
> +            throw new CommonException(ErrorCode.INVALID_ROLE_OF_USER);
네 승구님의 코드리뷰를 받아 이 부분을 @Login Parent parent 와 같이 수정하였습니다.
저 부분은 삭제하였습니다!

2024-02-18 05:39 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/controller/PickUpController.java
> +            throw new CommonException(ErrorCode.INVALID_ROLE_OF_USER);
네 승구님의 코드리뷰를 받아 이 부분을 @Login Parent parent 와 같이 수정하였습니다.
저 부분은 삭제하였습니다!

2024-02-18 05:40 UTC, eekrwl commented on BE/iDrop/src/main/java/ifive/idrop/controller/PickUpController.java
> +                            .childImage(child.getName())
큰 실수를 했네요! 알려주셔서 감사합니다 수정했습니다:)

2024-02-18 05:42 UTC, eekrwl commented
### merge 취소
상의 결과 정보조회에 상황에 따라 총 4개의 url을 사용하던 부분을 한개로 줄이기로 하였습니다.
이 이슈의 merge는 취소하되, 브랜치만 일단 남겨두겠습니다!

2024-02-18 05:43 UTC, eekrwl commented
merge 취소
상의 결과 정보조회에 상황에 따라 총 4개의 url을 사용하던 부분을 한개로 줄이기로 하였습니다.
이 이슈의 merge는 취소하되, 브랜치만 일단 남겨두겠습니다!

2024-02-18 05:43 UTC, closed without merging